name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          commit_message: "Update snake animation"
          committer: "${{ secrets.USER_NAME }} <${{ secrets.USER_EMAIL }}>"
          author: "${{ secrets.USER_NAME }} <${{ secrets.USER_EMAIL }}>"
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}